var fs=require("fs");
var j=fs.readFileSync("public/main.js","utf8");

// Remove all old voice functions
j=j.replace(/var voiceOn[\s\S]*$/,"");

// Add new simple voice code that matches the working test pattern
j+='\n\nvar voiceOn=false,voiceSession=[];\n';
j+='function voiceListen(){\n';
j+='  var s=document.getElementById("voiceStatus");\n';
j+='  var h=document.getElementById("voiceHeard");\n';
j+='  s.textContent="Listening...";\n';
j+='  document.getElementById("voiceMicBtn").className="listening";\n';
j+='  var SR=window.SpeechRecognition||window.webkitSpeechRecognition;\n';
j+='  var rec=new SR();\n';
j+='  rec.lang="en-US";\n';
j+='  rec.onresult=function(e){\n';
j+='    var text=e.results[0][0].transcript;\n';
j+='    h.textContent=text;\n';
j+='    s.textContent="Processing...";\n';
j+='    document.getElementById("voiceMicBtn").className="thinking";\n';
j+='    var r=parseVoiceTranscript(text);\n';
j+='    if(r.size||r.brand){\n';
j+='      if(r.quantity&&r.quantity>0){\n';
j+='        voiceSaveEntry(r).then(function(){\n';
j+='          s.textContent="+"+r.quantity+" "+r.brand+" "+r.size;\n';
j+='          document.getElementById("voiceMicBtn").className="success";\n';
j+='          if(voiceOn)setTimeout(voiceListen,1500);\n';
j+='        });\n';
j+='      }else{\n';
j+='        s.textContent=r.brand+" "+r.size+" - how many?";\n';
j+='        document.getElementById("voiceMicBtn").className="asking";\n';
j+='      }\n';
j+='    }else{\n';
j+='      s.textContent="Didn\'t catch that";\n';
j+='      if(voiceOn)setTimeout(voiceListen,1000);\n';
j+='    }\n';
j+='  };\n';
j+='  rec.onerror=function(e){s.textContent="MIC ERROR: "+e.error;document.getElementById("voiceMicBtn").className="";};\n';
j+='  rec.onend=function(){if(voiceOn&&document.getElementById("voiceMicBtn").className==="listening")setTimeout(voiceListen,500);};\n';
j+='  rec.start();\n';
j+='}\n';
j+='window.voiceToggle=function(){\n';
j+='  if(voiceOn){voiceOn=false;document.getElementById("voiceStatus").textContent="Stopped";document.getElementById("voiceMicBtn").className="";return;}\n';
j+='  voiceOn=true;\n';
j+='  voiceListen();\n';
j+='};\n';
j+='async function voiceSaveEntry(entry){\n';
j+='  var sku=[entry.brand,entry.model,entry.size,entry.position||"",entry.condition||""].map(function(x){return(x||"").toLowerCase().trim();}).join("|");\n';
j+='  try{\n';
j+='    var ref=await db.collection("movements").add({timestamp:firebase.firestore.FieldValue.serverTimestamp(),userId:currentUser.uid,userEmail:currentUser.email,brand:entry.brand,model:entry.model||"",size:entry.size,position:entry.position||"",condition:entry.condition||"New",zone:"",qty:entry.quantity,source:"count",notes:"Voice count",sku:sku});\n';
j+='    entry.fid=ref.id;\n';
j+='    onHandCache[sku]=(onHandCache[sku]||0)+entry.quantity;\n';
j+='  }catch(e){document.getElementById("voiceStatus").textContent="Error: "+e.message;return;}\n';
j+='  voiceSession.unshift(entry);\n';
j+='  voiceRenderLog();\n';
j+='}\n';
j+='window.voiceUndo=async function(){\n';
j+='  if(!voiceSession.length)return;\n';
j+='  var last=voiceSession.shift();\n';
j+='  if(last.fid){try{await db.collection("movements").doc(last.fid).delete();}catch(e){}var sku=[last.brand,last.model,last.size,last.position||"",last.condition||""].map(function(x){return(x||"").toLowerCase().trim();}).join("|");onHandCache[sku]=(onHandCache[sku]||0)-last.quantity;}\n';
j+='  voiceRenderLog();\n';
j+='  document.getElementById("voiceStatus").textContent="Removed "+last.brand+" "+last.size;\n';
j+='};\n';
j+='window.voiceClear=function(){voiceSession=[];voiceRenderLog();};\n';
j+='function voiceRenderLog(){\n';
j+='  var el=document.getElementById("voiceLog");\n';
j+='  var total=voiceSession.reduce(function(s,e){return s+(e.quantity||0);},0);\n';
j+='  document.getElementById("voiceSessionCount").textContent=total+" tires";\n';
j+='  if(!voiceSession.length){el.innerHTML="No entries yet";return;}\n';
j+='  el.innerHTML=voiceSession.map(function(e){return "<div style=\\"display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #333\\"><span><b style=\\"color:#0f0\\">"+e.brand+"</b> "+(e.model||"")+" <code>"+e.size+"</code></span><span style=\\"font-size:20px;font-weight:bold\\">+"+e.quantity+"</span></div>";}).join("");\n';
j+='}\n';
fs.writeFileSync("public/main.js",j);
console.log("DONE");
